
const LESSONPLANDATA = [
    {
        id: '1',
        name: 'Digital Marketing',
        day: 'Mon,Tue,Wed,Thurs,Fri,Sat,Sun',
        lessonplan: 'Lesson plan goes here come and join us',
        objective: 'Objective goes here come and join us',
        activities: 'Activities goes here come and join us',
        notes: 'Notes goes here come and join us',
    },
    {
        id: '2',
        name: 'Digital Marketing',
        day: 'Mon,Tue,Wed,Thurs,Fri,Sat,Sun',
        lessonplan: 'Lesson plan goes here come and join us',
        objective: 'Objective goes here come and join us',
        activities: 'Activities goes here come and join us',
        notes: 'Notes goes here come and join us',
    },
    {
        id: '3',
        name: 'Digital Marketing',
        day: 'Mon,Tue,Wed,Thurs,Fri,Sat,Sun',
        lessonplan: 'Lesson plan goes here come and join us',
        objective: 'Objective goes here come and join us',
        activities: 'Activities goes here come and join us',
        notes: 'Notes goes here come and join us',
    },
    {
        id: '4',
        name: 'Digital Marketing',
        day: 'Mon,Tue,Wed,Thurs,Fri,Sat,Sun',
        lessonplan: 'Lesson plan goes here come and join us',
        objective: 'Objective goes here come and join us',
        activities: 'Activities goes here come and join us',
        notes: 'Notes goes here come and join us',
    },
    {
        id: '5',
        name: 'Digital Marketing',
        day: 'Mon,Tue,Wed,Thurs,Fri,Sat,Sun',
        lessonplan: 'Lesson plan goes here come and join us',
        objective: 'Objective goes here come and join us',
        activities: 'Activities goes here come and join us',
        notes: 'Notes goes here come and join us',
    },
    {
        id: '6',
        name: 'Digital Marketing',
        day: 'Mon,Tue,Wed,Thurs,Fri,Sat,Sun',
        lessonplan: 'Lesson plan goes here come and join us',
        objective: 'Objective goes here come and join us',
        activities: 'Activities goes here come and join us',
        notes: 'Notes goes here come and join us',
    },
    {
        id: '7',
        name: 'Digital Marketing',
        day: 'Mon,Tue,Wed,Thurs,Fri,Sat,Sun',
        lessonplan: 'Lesson plan goes here come and join us',
        objective: 'Objective goes here come and join us',
        activities: 'Activities goes here come and join us',
        notes: 'Notes goes here come and join us',
    },
    {
        id: '8',
        name: 'Digital Marketing',
        day: 'Mon,Tue,Wed,Thurs,Fri,Sat,Sun',
        lessonplan: 'Lesson plan goes here come and join us',
        objective: 'Objective goes here come and join us',
        activities: 'Activities goes here come and join us',
        notes: 'Notes goes here come and join us',
    },
    {
        id: '9',
        name: 'Digital Marketing',
        day: 'Mon,Tue,Wed,Thurs,Fri,Sat,Sun',
        lessonplan: 'Lesson plan goes here come and join us',
        objective: 'Objective goes here come and join us',
        activities: 'Activities goes here come and join us',
        notes: 'Notes goes here come and join us',
    },
    {
        id: '10',
        name: 'Digital Marketing',
        day: 'Mon,Tue,Wed,Thurs,Fri,Sat,Sun',
        lessonplan: 'Lesson plan goes here come and join us',
        objective: 'Objective goes here come and join us',
        activities: 'Activities goes here come and join us',
        notes: 'Notes goes here come and join us',
    },
    {
        id: '11',
        name: 'Digital Marketing',
        day: 'Mon,Tue,Wed,Thurs,Fri,Sat,Sun',
        lessonplan: 'Lesson plan goes here come and join us',
        objective: 'Objective goes here come and join us',
        activities: 'Activities goes here come and join us',
        notes: 'Notes goes here come and join us',
    },
    {
        id: '12',
        name: 'Digital Marketing',
        day: 'Mon,Tue,Wed,Thurs,Fri,Sat,Sun',
        lessonplan: 'Lesson plan goes here come and join us',
        objective: 'Objective goes here come and join us',
        activities: 'Activities goes here come and join us',
        notes: 'Notes goes here come and join us',
    },
    {
        id: '13',
        name: 'Digital Marketing',
        day: 'Mon,Tue,Wed,Thurs,Fri,Sat,Sun',
        lessonplan: 'Lesson plan goes here come and join us',
        objective: 'Objective goes here come and join us',
        activities: 'Activities goes here come and join us',
        notes: 'Notes goes here come and join us',
    },
    {
        id: '14',
        name: 'Digital Marketing',
        day: 'Mon,Tue,Wed,Thurs,Fri,Sat,Sun',
        lessonplan: 'Lesson plan goes here come and join us',
        objective: 'Objective goes here come and join us',
        activities: 'Activities goes here come and join us',
        notes: 'Notes goes here come and join us',
    },
]

export default LESSONPLANDATA