const MacBookProData = [
  {
    id: 1,
    question: "Why use React instead of other frameworks, like Angular?",
    a: "Because React is the best",
    b: "Because React is very fast",
    c: "Because React is refreshingly dope",
  },
  {
    id: 2,
    question: "Why use React instead of other frameworks, like Angular?",
    a: "Because React is the best",
    b: "Because React is very fast",
    c: "Because React is refreshingly dope",
  },
  {
    id: 3,
    question: "Why use React instead of other frameworks, like Angular?",
    a: "Because React is the best",
    b: "Because React is very fast",
    c: "Because React is refreshingly dope",
  },
  {
    id: 4,
    question: "Why use React instead of other frameworks, like Angular?",
    a: "Because React is the best",
    b: "Because React is very fast",
    c: "Because React is refreshingly dope",
  },
  {
    id: 5,
    question: "Why use React instead of other frameworks, like Angular?",
    a: "Because React is the best",
    b: "Because React is very fast",
    c: "Because React is refreshingly dope",
  },
  {
    id: 6,
    question: "Why use React instead of other frameworks, like Angular?",
    a: "Because React is the best",
    b: "Because React is very fast",
    c: "Because React is refreshingly dope",
  },
  {
    id: 7,
    question: "Why use React instead of other frameworks, like Angular?",
    a: "Because React is the best",
    b: "Because React is very fast",
    c: "Because React is refreshingly dope",
  },
  {
    id: 8,
    question: "Why use React instead of other frameworks, like Angular?",
    a: "Because React is the best",
    b: "Because React is very fast",
    c: "Because React is refreshingly dope",
  },
  {
    id: 9,
    question: "Why use React instead of other frameworks, like Angular?",
    a: "Because React is the best",
    b: "Because React is very fast",
    c: "Because React is refreshingly dope",
  },
  {
    id: 10,
    question: "Why use React instead of other frameworks, like Angular?",
    a: "Because React is the best",
    b: "Because React is very fast",
    c: "Because React is refreshingly dope",
  },
];
export default MacBookProData;
